version: 2.0
jobs:
  build:
    docker:
      - image: cibuilds/hugo:latest
    working_directory: ~/hugo
    environment:
      HUGO_BUILD_DIR: public/
    steps:
      - run:
          name: Update apt
          command: |
            sudo apt-get update
            sudo apt-get install -y git python3 python3-pip
      - run:
          name: Install awscli
          command: pip3 install awscli
      - checkout
      - run:
          name: Update git submodules
          command: |
            git submodule sync
            git submodule update --init --recursive
      - run:
          name: Hugo build
          command: HUGO_ENV=production hugo -v -d $HUGO_BUILD_DIR
      - deploy:
          name: Deploy to AWS
          command: |
            if [ "${CIRCLE_BRANCH}" = "main" ]; then
              hugo deploy
            else
              echo "Not main branch, dry run only"
            fi
